name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')  # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/support')  # check the comment if it contains the keywords
        run: |
          echo say hello

      - name: test
        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
        run: |
          echo test
  check_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Pull Requests
        run: |
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/gkathiravan/command_operated/pulls?state=open | jq -r '.[] | select(.labels[].name == "Ready to Merge") | .head.ref'')
          
          # Do something with the $PRS variable, e.g., print the list of PRs
          echo "Pull Requests with 'Ready to Merge' label:"
          echo "$PRS"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
