name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')  # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/support')  # check the comment if it contains the keywords
        run: |
          echo say hello

      - name: test
        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
        run: |
          echo test
  fetch-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch existing comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching comments from the PR Conversation tab..."
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq '.[] | {id, body, created_at} | "Comment ID: \(.id)\nCreated At: \(.created_at)\nBody: \(.body)\n---"' \
            | tee comments.log

      - name: Output comments
        run: |
          echo "Comments fetched from the Conversation tab:"
          cat comments.log
