name: Fetch Commit IDs

on:
  push:
    branches:
      - main

jobs:
  fetch-commit-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and display last 25 commit IDs
        run: |
          commit_ids=($(git log -n 25 --format="%H"))
          echo "Commit IDs:"
          for id in "${commit_ids[@]}"; do
            echo "$id"
          done
