name: Fetch Commit IDs

on:
  push:
    branches:
      - main

jobs:
  fetch-commit-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch last 25 commit IDs
        id: fetch-commits
        run: |
          commit_ids=($(git log -n 25 --format="%H"))
          echo "commit_ids=(${commit_ids[@]})" >> $GITHUB_ENV

      - name: Display commit IDs
        run: |
          echo "Commit IDs: ${commit_ids[@]}"
